name: Deploy GitHub pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate HTML docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "doc/"
          pre-build-command: |
            apt-get update
            pip install -r requirements.txt
            pip install -e ".[docs]"
      - name: Upload generated HTML as artifact
        uses: actions/upload-artifact@v2
        with:
          name: DocHTML
          path: doc/_build/html/
